### ISSUE TITLE
Client crash on startup

### ISSUE THREAD

**Issue by xnacly** [Haizor/hypixel-fishing-log#2]
Crash report shows your mod as the cause.
`
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:176)
	at com.google.gson.Gson.fromJson(Gson.java:803)
	at com.google.gson.Gson.fromJson(Gson.java:741)
	at net.haizor.hypixelfishinglog.data.DataManager.init(DataManager.java:33)
	at net.haizor.hypixelfishinglog.FishingLog.init(FishingLog.java:27)
`

Full Log:
[crash-2020-06-25_10.19.21-client.txt](https://github.com/Haizor/hypixel-fishing-log/files/4829983/crash-2020-06-25_10.19.21-client.txt)

**Comment by Haizor** [comment]
Fixed!
